language: java
jdk:
- oraclejdk12
deploy:
  provider: heroku
  api_key:
    secure: mLsqyGaXcVhHstd8NiDST1gEP3FX+8A1jYDasGADVWkPqJAhP2hHO2xFG/lvx6x/MHGqUePYF3M4QDvnS4jZfWhWgYvJi0HiPJDuI+PvLE7/tO1vwqp1cKFnFoJG4R8lA0c4XFeXBD5pSKE1/2sHwrWiSxZGUpSrSE8vsZ5+6HXuWUQkyKQHgjEA0rWAE2TuGMEbthGEGCgAYzGT5Nn7zkWIzDwBQSR5lnQISMDLCAdEI4D6myROla9IL+oFWMvvapjg6ZWP+JBsjztOiEHhnfl0hHlMMdVHrGFbojmgmB+4G944/YTy0wKDiI3Df8XS9/SResAlFLBCmER1mgOkUmdGrHHPk7+MJ2r1KpKrrbmc0Wt1LfqiBQD2g3Tq8A5yJZRfBcaud5NppU++qTM8EOftq4URFe2aPiiCdj6fZKLOK/0Ew4tUtISqUHfLYjm0c2jNLpV4jy5SdGTIBgZGVlK2TPJVB3dJXzxYVGJm5HsEQjWMU/BmqYKQV/ejjc3yEvUEGeGK3Zrgxm6Cbg6OWm2/laLaZguJC9n4xOmZgjdQVVVUgBMlcE5QEKK6HY3Y2BLZVles8Zrr7z8dxuZUllRKqNrmFRadbQetw3wsvauOwrdjAF672w8kKCIB/Pdq/QQEJF23YjtEG78WXwPXj//hWwoJnmhpeG0X1PoMmfg=
  app: overunderleague
