language: java
jdk:
- oraclejdk12
deploy:
  provider: heroku
  api_key:
    secure: HyJVHPLJlLxcBHsA1Ih3cWWY9L2UE0FgNMQ9F74/9xA21pk1srXokvEy//JniupMbSwp5Ls+WQkwDTVUOJVCYoIlEPhz/q17AtnZ7oAhkOtlzUg5ulADtiJL8mym0osCSpaa1ertkhPAfu5iJjOL9QkpVdCYSVbs4YfwdzVA8WI7RbBKZu4XCsIBsfc42rN1pJnPAeg26MFt+MfUFIBl+054sRICHOqYr3ikaizzmAerNXvvs3KiRV5GE+HmdJhUDUqena5aGbCA8M9vOduIqbyiNEPcMw63A8/C93gdfj1bH9QvKbVjEsctKJzbWTocci+qbvBcY9S6bx+zFKeli1cpKPhfeoagVpkArXXqAZDky2fHGXQ6m0iTohlmXVrDyxywvXU21Q/zEAeXpUbm1JOBt1nONhXDix3Z3MtdAYzk/NsSpTpFwV/lzUfPtOSWvrE03oqhEcdN8GUxJqXCNjWkla4FlHiU6yJ1eezaEfbL8ShwOMCDs5ZaJvw+ZCTndkOCJttdXiNguXxPcQ3fxRFvbNYsoiJEQIG5DEiHMBSFE1Au1sTSavxalYyt7GSsBPi1/AtOySC4XLi3jM8B7QlLynWUEPCLlhP3bx5l8+9gAQg9hxfO6UsstLUPEW9AIPUBdtFh0fjTb2YfE5meFTXj9pZozDWi0DeMLU+AY2k=
  app: overunderleague
