language: java
jdk:
- oraclejdk12
deploy:
  provider: heroku
  api_key:
    secure: BKVdvf7FFhLGaBqRI/hXaweX+Ll8xUSQ5DZ0o/QyxqcA5vKKkB14qcq5V1ZSqOo0YEg4LkKCP5qdz6lMSwkvg07r5trlSsgk1K+HDhiEBcm8iIyaho1iwek7yQyC5yINRegyEbB5B2P6NIV/wY5Rbj0FA38GUI6/KPdEWRJDYX1ZMg8pNEwBL7LYegiFZifiHIUNc7lc6s8Fn+ho0THIN+g6zYm0cUiytiUp1GXoaoBPulVjcWM5pJrTkxXwzwxH0r+SjcrT+MGgw+a1yGcqZXuIDyF4zK+gUJ1LWd0oMj88CAV6j8NtfEhp5LxKEZFITKlp+ZMP/Gjy5e+/FRol9fFbNGLV/YIEAA0Gk7nVxRntyJCc8v9eOXMb1bVeY4EAp52cEbLA54wTYO5kAXrKZYLmmL6T8tx2TW4TN2wcOnSSe2yvqBSW1tjh+/XFOw6dS/CyzgfxlsX8OHOCkBJ6tdw0bg2UUET9CCVJoykdOCC1hKiKTJdLbJT0raegPTKLXomw9EACgL0Gl+7lmlfjl/jXz8BV49POj1zjmYsqkJ7zzmZw8xcxNFcHrEQVbNxc/oRdO5jNh4c/KCQtbj/WBZ9YIadFfpf8sHoQW8SP1NkwAxFyuk3nyA7kBSHoJX6LdwrR3HhKtmfLzimY7ZOQWP6ivJKl/Nbh8IubjEiX9hU=
  app: overunderleague
  on:
    repo: Jimeh87/over-under-league
