version: 2.1

executors:
  java:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: small

jobs:
  build:
    executor: java
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
      - run:
          name: Build and test
          command: ./mvnw clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/over-under-league.jar
          destination: .
  deploy:
    executor: java
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
      - run:
          name: Build docker image
          command: ./mvnw spring-boot:build-image
      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: List docker images
          command: |
            docker images
      - run:
          name: Push docker image
          command: |
            docker push jimeh87/overunderleague:2.0.0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy
