version: 2.1

executors:
  java:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: small

jobs:
  build:
    executor: java
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
      - run:
          name: Build and Test
          command: mvn clean install
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}
      - store_artifacts:
          path: target
          destination: build-artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
