version: 2.1

orbs:
  maven: circleci/maven@2.0.0

jobs:
  deploy:
    docker:
      - image: cimg/base:2022.10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "3b:44:a2:86:3e:b0:46:17:85:7a:33:1d:2a:b3:91:b0"
      - run: bash ./scripts/deploy.sh
    executor: 21.0.5

workflows:
  build-and-deploy:
    jobs:
      - maven/test:
          name: build
          test_results_path: target/surefire-reports
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - target/over-under-league.jar
            - store_artifacts:
                path: target/over-under-league.jar
                destination: jar
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
